version: "3"

services:
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd app && yarn && yarn start"
    ports:
      - "4000:3000"
